apiVersion: v1
kind: Service
metadata:
  name: cleanuparr
spec:
  type: LoadBalancer
  selector:
    app: cleanuparr
    component: server
  ports:
    - name: http
      port: 11011

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanuparr
  labels:
    app: cleanuparr
    component: server
spec:
  selector:
    matchLabels:
      app: cleanuparr
      component: server
  template:
    metadata:
      labels:
        app: cleanuparr
        component: server
    spec:
      containers:
        - name: cleanuparr
          image: ghcr.io/cleanuparr/cleanuparr:2.4
          env:
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
          ports:
            - name: http
              containerPort: 11011
          volumeMounts:
            - name: data
              mountPath: /config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: cleanuparr-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
