apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  type: ClusterIP
  selector:
    app: flaresolverr
    component: server
  ports:
    - name: http
      port: 8191

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: flaresolverr
    component: server
spec:
  selector:
    matchLabels:
      app: flaresolverr
      component: server
  template:
    metadata:
      labels:
        app: flaresolverr
        component: server
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:v3.4.6
          env:
            - name: "TZ"
              value: "America/Los_Angeles"
          ports:
            - name: http
              containerPort: 8191
