apiVersion: v1
kind: Service
metadata:
  name: huntarr
spec:
  type: LoadBalancer
  selector:
    app: huntarr
    component: server
  ports:
    - name: http
      port: 9705

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huntarr
  labels:
    app: huntarr
    component: server
spec:
  selector:
    matchLabels:
      app: huntarr
      component: server
  template:
    metadata:
      labels:
        app: huntarr
        component: server
    spec:
      containers:
        - name: huntarr
          image: huntarr/huntarr:8.2.10
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          env:
            - name: HUNTARR_PORT
              value: "9705"
          ports:
            - name: http
              containerPort: 9705
          volumeMounts:
            - name: data
              mountPath: /config
            - name: backups
              mountPath: /config/backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: huntarr-data
        - name: backups
          hostPath:
            path: /mnt/backups/huntarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huntarr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
