apiVersion: v1
kind: Service
metadata:
  name: nzbget
spec:
  type: LoadBalancer
  selector:
    app: nzbget
    component: server
  ports:
    - name: http
      port: 6789

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  labels:
    app: nzbget
    component: server
spec:
  selector:
    matchLabels:
      app: nzbget
      component: server
  template:
    metadata:
      labels:
        app: nzbget
        component: server
    spec:
      containers:
        - name: nzbget
          image: lscr.io/linuxserver/nzbget:25.4.20251212
          env:
            - name: "PUID"
              value: "1000"
            - name: "PGID"
              value: "1000"
            - name: "TZ"
              value: "America/Los_Angeles"
          ports:
            - name: http
              containerPort: 6789
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /mnt/media
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nzbget-data
        - name: media
          hostPath:
            path: /mnt/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
