apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  type: LoadBalancer
  selector:
    app: prowlarr
    component: server
  ports:
    - name: http
      port: 9696

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  labels:
    app: prowlarr
    component: server
spec:
  selector:
    matchLabels:
      app: prowlarr
      component: server
  template:
    metadata:
      labels:
        app: prowlarr
        component: server
    spec:
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr:2.1.5
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 9696
          volumeMounts:
            - name: data
              mountPath: /config
            - name: backups
              mountPath: /backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: prowlarr-data
        - name: backups
          hostPath:
            path: /mnt/backups/prowlarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
