apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
spec:
  type: LoadBalancer
  selector:
    app: qbittorrent
    component: server
  ports:
    - name: http
      port: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  labels:
    app: qbittorrent
    component: server
spec:
  selector:
    matchLabels:
      app: qbittorrent
      component: server
  template:
    metadata:
      labels:
        app: qbittorrent
        component: server
    spec:
      containers:
        - name: qbittorrent
          image: linuxserver/qbittorrent:5.1.4
          env:
            - name: TZ
              value: "America/Los_Angeles"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /mnt/media
        - name: wireguard
          image: linuxserver/wireguard:1.0.20250521
          securityContext:
            # getting error `sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"`
            privileged: true
          volumeMounts:
            - name: wireguardconfig
              mountPath: /config/wg_confs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: qbittorrent-data
        - name: media
          hostPath:
            path: /mnt/media
        - name: wireguardconfig
          secret:
            secretName: qbittorrent-wireguard-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
