apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  type: LoadBalancer
  selector:
    app: radarr
    component: server
  ports:
    - name: http
      port: 7878

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  labels:
    app: radarr
    component: server
spec:
  selector:
    matchLabels:
      app: radarr
      component: server
  template:
    metadata:
      labels:
        app: radarr
        component: server
    spec:
      containers:
        - name: radarr
          image: linuxserver/radarr:6.0.4
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 7878
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /mnt/media
            - name: backups
              mountPath: /backups
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: radarr-data
        - name: media
          hostPath:
            path: /mnt/media
        - name: backups
          hostPath:
            path: /mnt/backups/radarr

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
