apiVersion: v1
kind: Service
metadata:
  name: seerr
spec:
  type: LoadBalancer
  selector:
    app: seerr
    component: server
  ports:
    - name: http
      port: 5055

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seerr
  labels:
    app: seerr
    component: server
spec:
  selector:
    matchLabels:
      app: seerr
      component: server
  template:
    metadata:
      labels:
        app: seerr
        component: server
    spec:
      containers:
        - name: seerr
          image: seerr/seerr:develop
          env:
            - name: TZ
              value: "America/Los_Angeles"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 5055
          volumeMounts:
            - name: data
              mountPath: /app/config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: seerr-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
