apiVersion: v1
kind: Service
metadata:
  name: transmission
spec:
  type: LoadBalancer
  selector:
    app: transmission
    component: server
  ports:
    - name: http
      port: 9091

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission
  labels:
    app: transmission
    component: server
spec:
  selector:
    matchLabels:
      app: transmission
      component: server
  template:
    metadata:
      labels:
        app: transmission
        component: server
    spec:
      containers:
        - name: transmission
          image: linuxserver/transmission:4.0.6
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: PEERPORT
              value: "62250"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          ports:
            - name: http
              containerPort: 9091
          volumeMounts:
            - name: data
              mountPath: /config
            - name: media
              mountPath: /mnt/media
        - name: wireguard
          image: linuxserver/wireguard:1.0.20250521
          securityContext:
            # getting error `sysctl: permission denied on key "net.ipv4.conf.all.src_valid_mark"`
            privileged: true
          volumeMounts:
            - name: wireguardconfig
              mountPath: /config/wg_confs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: transmission-data
        - name: media
          hostPath:
            path: /mnt/media
        - name: wireguardconfig
          secret:
            secretName: transmission-wireguard-config

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
