apiVersion: v2
name: monitoring
version: 0.1.0

dependencies:
- name: grafana
  version: "7.3.2"
  repository: "https://grafana.github.io/helm-charts"

- name: loki
  version: "5.43.3"
  repository: "https://grafana.github.io/helm-charts"

- name: promtail
  version: "6.15.5"
  repository: "https://grafana.github.io/helm-charts"

- name: prometheus
  version: "25.14.0"
  repository: https://prometheus-community.github.io/helm-charts

