apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: brennonloveless
    layer: service
  name: brennonloveless
spec:
  replicas: 1
  selector:
    matchLabels:
      component: brennonloveless
      layer: service
  template:
    metadata:
      labels:
        component: brennonloveless
        layer: service
    spec:
      containers:
      - name: brennonloveless
        image: bloveless/brennonloveless-com:{{ .Values.ImageTag }}
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
