apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brennonloveless
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
  - host: "brennonloveless.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: brennonloveless
            port:
              number: 80
  tls:
  - hosts:
    - brennonloveless.com
    secretName: brennonloveless-cert
