apiVersion: v1
kind: Service
metadata:
    name: brennonloveless
spec:
    selector:
      component: brennonloveless
      layer: service
    ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
