overseerr:
  enabled: true
  image: sctx/overseerr:1.33.2

prowlarr:
  enabled: true
  image: linuxserver/prowlarr:1.13.3

qbittorrent:
  enabled: true
  image: linuxserver/qbittorrent:4.6.3

radarr:
  enabled: true
  image: linuxserver/radarr:5.2.6

sabnzbd:
  enabled: true
  image: linuxserver/sabnzbd:4.2.2

sonarr:
  enabled: true
  image: linuxserver/sonarr:4.0.1

wireguard:
  image: linuxserver/wireguard:1.0.20210914

flaresolverr:
  enabled: true
  image: flaresolverr/flaresolverr:v3.3.15
