{{ if .Values.bazarr.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-bazarr-config
  labels:
    type: local
    app: media-server
    component: bazarr
    volume: config
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/bazarr/config
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: bazarr
      volume: config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
spec:
  selector:
    app: media-server
    component: bazarr
  ports:
    - name: http
      port: 6767

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bazarr
  labels:
    app: media-server
    component: bazarr
  annotations:
    projectcontour.io/response-timeout: "2m"
spec:
  ingressClassName: contour
  rules:
  - host: bazarr.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bazarr
            port:
              number: 6767

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  labels:
    app: media-server
    component: bazarr
spec:
  selector:
    matchLabels:
      app: media-server
      component: bazarr
  template:
    metadata:
      labels:
        app: media-server
        component: bazarr
    spec:
      containers:
      - name: bazarr
        image: bazarr
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 6767
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: bazarr-config
      - name: downloads
        persistentVolumeClaim:
          claimName: plex-data

{{ end }}
