{{- if .Values.flaresolverr.enabled}}
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
spec:
  selector:
    app: media-server
    component: flaresolverr
  ports:
  - protocol: TCP
    port: 8191
    targetPort: 8191
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: media-server
    component: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: flaresolverr
  template:
    metadata:
      labels:
        app: media-server
        component: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: {{ .Values.flaresolverr.image }}
        ports:
        - containerPort: 8191
        env:
        - name: LOG_LEVEL
          value: info
        - name: LOG_HTML
          value: "false"
        - name: CAPTCHA_SOLVER
          value: none
        - name: TZ
          value: "America/Los_Angeles"
{{- end}}
