{{ if .Values.jackett.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-jackett-downloads
  labels:
    type: local
    app: media-server
    component: jackett
    volume: downloads
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/jackett/storage
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-jackett-config
  labels:
    type: local
    app: media-server
    component: jackett
    volume: config
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/jackett/config
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: jackett
      volume: config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jackett-downloads
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: jackett
      volume: downloads
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: jackett
spec:
  selector:
    app: media-server
    component: jackett
  ports:
  - name: http
    port: 9117

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jackett
  labels:
    app: media-server
    component: jackett-ingress
  annotations:
    projectcontour.io/response-timeout: "2m"
spec:
  ingressClassName: contour
  rules:
  - host: jackett.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jackett
            port:
              number: 9117

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jackett
  labels:
    app: media-server
    component: jackett
spec:
  selector:
    matchLabels:
      app: media-server
      component: jackett
  template:
    metadata:
      labels:
        app: media-server
        component: jackett
    spec:
      containers:
      - name: jackett
        image: jackett
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 9117
        volumeMounts:
        - name: config
          mountPath: /config
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jackett-config
      - name: downloads
        persistentVolumeClaim:
          claimName: jackett-downloads
{{ end }}
