{{ if .Values.overseerr.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-overseerr-config
  labels:
    type: local
    app: media-server
    component: overseerr
    volume: config
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/overseerr/config
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: overseerr
      volume: config
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
spec:
  selector:
    app: media-server
    component: overseerr
  ports:
  - name: http
    port: 5055

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseerr
  labels:
    app: media-server
    component: overseerr-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  tls:
  - hosts:
    - overseerr.brennonloveless.com
    secretName: overseerr-tls
  rules:
  - host: overseerr.brennonloveless.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: overseerr
            port:
              number: 5055

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseerr
  labels:
    app: media-server
    component: overseerr
spec:
  selector:
    matchLabels:
      app: media-server
      component: overseerr
  template:
    metadata:
      labels:
        app: media-server
        component: overseerr
    spec:
      containers:
      - name: overseerr
        image: overseerr
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 5055
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: overseerr-config
{{ end }}
