---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-plex-data
  labels:
    type: local
    app: media-server
    component: plex
    volume: data
spec:
  storageClassName: manual
  capacity:
    storage: 500G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/plex/data
  mountOptions:
    - soft
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-data
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: plex
      volume: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500G

