{{ if .Values.prowlarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-prowlarr-backups
  labels:
    type: local
    app: media-server
    component: prowlarr
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/prowlarr/backups
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: prowlarr
      volume: backups
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
spec:
  selector:
    app: media-server
    component: prowlarr
  ports:
    - name: http
      port: 9696

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prowlarr
  labels:
    app: media-server
    component: prowlarr
  annotations:
    projectcontour.io/response-timeout: "2m"
spec:
  ingressClassName: contour
  rules:
  - host: prowlarr.lan
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prowlarr
            port:
              number: 9696

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  labels:
    app: media-server
    component: prowlarr
spec:
  serviceName: prowlarr
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: prowlarr
  template:
    metadata:
      labels:
        app: media-server
        component: prowlarr
    spec:
      containers:
      - name: prowlarr
        image: prowlarr
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 9696
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backups
          mountPath: /backups
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prowlarr-config
      - name: backups
        persistentVolumeClaim:
          claimName: prowlarr-backups
{{ end }}
