{{ if .Values.qbittorrent.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-qbittorrent-config
  labels:
    type: local
    app: media-server
    component: qbittorrent
    volume: config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/qbittorrent/data
  mountOptions:
    - soft
    - nfsvers=4.1
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: qbittorrent
      volume: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: qbittorrent-wireguard-config
  namespace: media-server
spec:
  itemPath: "vaults/Homelab/items/Qbittorrent Wireguard Config"
---

apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-tcp
spec:
  selector:
    app: media-server
    component: qbittorrent
  ports:
    - name: webui
      port: 8080
    - name: incoming-tcp
      port: 6881
---

apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-udp
spec:
  selector:
    app: media-server
    component: qbittorrent
  ports:
    - name: incoming-udp
      port: 6881
      protocol: UDP
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  labels:
    app: media-server
    component: qbittorrent-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
    - host: qbittorrent.lan.brennonloveless.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-tcp
                port:
                  number: 8080
  tls:
  - hosts:
    - qbittorrent.lan.brennonloveless.com
    secretName: qbittorrent-cert
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent
  labels:
    app: media-server
    component: qbittorrent
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: media-server
      component: qbittorrent
  template:
    metadata:
      labels:
        app: media-server
        component: qbittorrent
    spec:
      hostname: media-server-torrent-downloader-1
      containers:
      - name: qbittorrent
        image: {{ .Values.qbittorrent.image }}
        resources:
          limits:
            memory: "1Gi"
        env:
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "America/Los_Angeles"
        ports:
          - name: webui
            containerPort: 8080
          - name: forwarded-port
            containerPort: 50274
          - name: incoming-tcp
            containerPort: 6881
            protocol: TCP
          - name: incoming-udp
            containerPort: 6881
            protocol: UDP
        volumeMounts:
          - name: config
            mountPath: /config
          - name: downloads
            mountPath: /downloads
      - name: wireguard
        image: {{ .Values.wireguard.image }}
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
        volumeMounts:
          - name: wireguardconfig
            mountPath: /config/wg_confs
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: qbittorrent-config
        - name: downloads
          persistentVolumeClaim:
            claimName: plex-data
        - name: wireguardconfig
          secret:
            secretName: qbittorrent-wireguard-config
{{ end }}
