{{ if .Values.radarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-radarr-backups
  labels:
    type: local
    app: media-server
    component: radarr
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/radarr/backups
  mountOptions:
    - soft
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: radarr
      volume: backups
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
spec:
  selector:
    app: media-server
    component: radarr
  ports:
  - name: http
    port: 7878

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
  labels:
    app: media-server
    component: radarr-ingress
  annotations:
    projectcontour.io/response-timeout: "2m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
  - host: radarr.lan.brennonloveless.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 7878
  tls:
  - hosts:
    - radarr.lan.brennonloveless.com
    secretName: radarr-cert

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: radarr-api-key
spec:
  itemPath: "vaults/Homelab/items/Radarr"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr
  labels:
    app: media-server
    component: radarr
  annotations:
    keel.sh/policy: minor
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
spec:
  serviceName: radarr
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: radarr
  template:
    metadata:
      labels:
        app: media-server
        component: radarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
      - name: radarr
        image: {{ .Values.radarr.image }}
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 7878
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backups
          mountPath: /backups
        - name: downloads
          mountPath: /downloads
      {{- if .Values.exportarr.enabled }}
      - name: exportarr
        image: {{ .Values.exportarr.image }}
        args:
          - radarr
        env:
          - name: PORT
            value: "9707"
          - name: URL
            value: "http://localhost:7878"
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: radarr-api-key
                key: api_key
        ports:
          - name: monitoring
            containerPort: 9707
        livenessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
      {{- end }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: backups
        persistentVolumeClaim:
          claimName: radarr-backups
      - name: downloads
        persistentVolumeClaim:
          claimName: plex-data
{{ end }}
