{{ if .Values.sabnzbd.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-sabnzbd-backups
  labels:
    type: local
    app: media-server
    component: sabnzbd
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/sabnzbd/backups
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: sabnzbd
      volume: backups
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-sabnzbd-config
  labels:
    type: local
    app: media-server
    component: sabnzbd
    volume: config
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/sabnzbd/data
  mountOptions:
    - soft
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-config
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: sabnzbd
      volume: config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sabnzbd-wireguard-config
spec:
  itemPath: "vaults/Homelab/items/Sabnzbd Wireguard Config"

---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
spec:
  selector:
    app: media-server
    component: sabnzbd
  ports:
    - name: http
      port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sabnzbd
  labels:
    app: media-server
    component: sabnzbd-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
    - host: sabnzbd.lan.brennonloveless.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sabnzbd
                port:
                  number: 8080
  tls:
    - hosts:
        - sabnzbd.lan.brennonloveless.com
      secretName: sabnzbd-cert

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sabnzbd-api-key
spec:
  itemPath: "vaults/Homelab/items/Sabnzbd"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sabnzbd
  labels:
    app: media-server
    component: sabnzbd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: media-server
      component: sabnzbd
  template:
    metadata:
      labels:
        app: media-server
        component: sabnzbd
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: sabnzbd
          image: {{ .Values.sabnzbd.image }}
          env:
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
            - name: backups
              mountPath: /backups
        - name: wireguard
          image: {{ .Values.wireguard.image }}
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: wireguardconfig
              mountPath: /config/wg_confs
        {{- if .Values.exportarr.enabled }}
        - name: exportarr
          image: {{ .Values.exportarr.image }}
          args:
            - sabnzbd
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://localhost:8080"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: sabnzbd-api-key
                  key: api_key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
        {{- end }}
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: sabnzbd-config
        - name: downloads
          persistentVolumeClaim:
            claimName: plex-data
        - name: wireguardconfig
          secret:
            secretName: sabnzbd-wireguard-config
        - name: backups
          persistentVolumeClaim:
            claimName: sabnzbd-backups
---
{{ end }}
