{{ if .Values.sonarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-sonarr-backups
  labels:
    type: local
    app: media-server
    component: sonarr
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/sonarr/backups
  mountOptions:
    - soft
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: sonarr
      volume: backups
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: media-server
    component: sonarr
  ports:
    - name: http
      port: 8989

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app: media-server
    component: sonarr
  annotations:
    projectcontour.io/response-timeout: "2m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
  - host: sonarr.lan.brennonloveless.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
  tls:
  - hosts:
    - sonarr.lan.brennonloveless.com
    secretName: sonarr-cert

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  labels:
    app: media-server
    component: sonarr
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: sonarr
  template:
    metadata:
      labels:
        app: media-server
        component: sonarr
    spec:
      containers:
      - name: sonarr
        image: {{ .Values.sonarr.image }}
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 8989
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backups
          mountPath: /backups
        - name: downloads
          mountPath: /downloads
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: backups
        persistentVolumeClaim:
          claimName: sonarr-backups
      - name: downloads
        persistentVolumeClaim:
          claimName: plex-data
{{ end }}
