{{ if .Values.sonarr.enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-server-sonarr-backups
  labels:
    type: local
    app: media-server
    component: sonarr
    volume: backups
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/media-server/sonarr/backups
  mountOptions:
    - soft
    - nfsvers=4.1

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-backups
spec:
  storageClassName: manual
  selector:
    matchLabels:
      app: media-server
      component: sonarr
      volume: backups
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G

---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
spec:
  selector:
    app: media-server
    component: sonarr
  ports:
    - name: http
      port: 8989

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr
  labels:
    app: media-server
    component: sonarr
  annotations:
    projectcontour.io/response-timeout: "2m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
  - host: sonarr.lan.brennonloveless.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sonarr
            port:
              number: 8989
  tls:
  - hosts:
    - sonarr.lan.brennonloveless.com
    secretName: sonarr-cert

---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: sonarr-api-key
spec:
  itemPath: "vaults/Homelab/items/Sonarr"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  labels:
    app: media-server
    component: sonarr
spec:
  serviceName: sonarr
  replicas: 1
  selector:
    matchLabels:
      app: media-server
      component: sonarr
  template:
    metadata:
      labels:
        app: media-server
        component: sonarr
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
      - name: sonarr
        image: {{ .Values.sonarr.image }}
        env:
        - name: TZ
          value: "America/Los_Angeles"
        ports:
        - name: http
          containerPort: 8989
        volumeMounts:
        - name: config
          mountPath: /config
        - name: backups
          mountPath: /backups
        - name: downloads
          mountPath: /downloads
      {{- if .Values.exportarr.enabled }}
      - name: exportarr
        image: {{ .Values.exportarr.image }}
        args:
          - sonarr
        env:
          - name: PORT
            value: "9707"
          - name: URL
            value: "http://localhost:8989"
          - name: APIKEY
            valueFrom:
              secretKeyRef:
                name: sonarr-api-key
                key: api_key
        ports:
          - name: monitoring
            containerPort: 9707
        livenessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: monitoring
          failureThreshold: 5
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
      {{- end }}
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: sonarr-config
      - name: backups
        persistentVolumeClaim:
          claimName: sonarr-backups
      - name: downloads
        persistentVolumeClaim:
          claimName: plex-data
{{ end }}
