apiVersion: v1
kind: Service
metadata:
  name: homelab-exporter
  labels:
    app: homelab-exporter
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
  - port: 9090
    protocol: TCP
  selector:
    app: homelab-exporter
