- name: Tools config
  hosts: tools
  tasks:
    - name: Install HAProxy
      package:
        name: haproxy
        state: present
      become: true

    - name: Configure HAProxy
      template:
        src: haproxy.cfg.jinja2
        dest: /etc/haproxy/haproxy.cfg
      become: true

    - name: Open port
      ansible.posix.firewalld:
        port: 6443/tcp
        permanent: true
        state: enabled
      become: true

    - name: SELinux allow kubernetes api on 6443
      community.general.seport:
        ports: 6443
        proto: tcp
        setype: http_port_t
        state: present
      become: true
