- name: Tools config
  hosts: tools
  become: true
  tasks:
    - name: Install dnf-plugins-core
      dnf:
        state: latest
        name: dnf-plugins-core

    - name: Add docker repository
      command: dnf config-manager addrepo --from-repofile https://download.docker.com/linux/fedora/docker-ce.repo
      args:
        creates: "/etc/yum.repos.d/docker-ce.repo"

    - name: Install docker
      dnf:
        state: latest
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create tools docker network
      docker_network:
        name: tools

    - name: Create haproxy docker config directory
      file:
        state: directory
        path: /opt/docker/haproxy

    - name: Copy haproxy config
      template:
        src: haproxy.cfg.jinja2
        dest: /opt/docker/haproxy/haproxy.cfg

    - name: Create tailscaled data directory
      file:
        state: directory
        path: /opt/docker/tailscaled/data

    - name: Create mariadb data directory
      file:
        state: directory
        path: /opt/docker/mariadb/data

    - name: Create newt data directory
      file:
        state: directory
        path: /opt/docker/newt/data

    - name: Add kubernetes repo
      copy:
        src: ./kubernetes.repo
        dest: /etc/yum.repos.d/kubernetes.repo

    - name: Install kubectl
      dnf:
        state: latest
        name:
          - kubectl

    - name: Make kubeconfig directory
      file:
        path: /home/brennon/.kube
        state: directory
        owner: brennon
        group: brennon

    - name: Copy kubeconfig
      copy:
        src: ~/.kube/config
        dest: /home/brennon/.kube/config

