repositories: []

helmfiles:
  - path: ./helmfile.init.yaml
  - path: ./helmfile.infra.yaml

releases:
- name: httpbin
  chart: ./charts/httpbin
  namespace: httpbin
  createNamespace: true

- name: brennonloveless
  chart: ./charts/brennonloveless
  namespace: brennonloveless
  createNamespace: true

- name: media-server
  chart: ./charts/media-server
  namespace: media-server

- name: homelab-exporter
  chart: ./charts/homelab-exporter
  namespace: homelab-exporter
  createNamespace: true
