---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-prometheus-data
  labels:
    type: local
    app: monitoring
    component: prometheus
    volume: data
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.115
    path: /volume1/homelab/monitoring/prometheus/data
  mountOptions:
    - soft
    - nfsvers=4.1
