---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
spec:
  storageClassName: {{.Values.uptimeKuma.persistentVolume.storageClass}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.uptimeKuma.persistentVolume.size}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
  labels:
    app: monitoring
    component: uptime-kuma
spec:
  selector:
    matchLabels:
      app: monitoring
      component: uptime-kuma
  template:
    metadata:
      labels:
        app: monitoring
        component: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: {{ .Values.uptimeKuma.image }}
        ports:
        - name: http
          containerPort: 3001
        volumeMounts:
        - name: data
          mountPath: /app/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: uptime-kuma-data

---
apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma
spec:
  selector:
    app: monitoring
    component: uptime-kuma
  ports:
    - name: http
      port: 3001

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  labels:
    app: monitoring
    component: uptime-kuma
  annotations:
    projectcontour.io/response-timeout: "2m"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: contour
  rules:
  - host: uptime-kuma.lan.brennonloveless.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uptime-kuma
            port:
              number: 3001
  tls:
  - hosts:
    - uptime-kuma.lan.brennonloveless.com
    secretName: uptime-kuma-cert

